import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Choose Plan Page",
    description: "Generated by brainwave-labs",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            { children }
        </>
    );
}